version: "3.1"
services:
  web:
    build: .
    environment:
      - OMDB_API_KEY
    ports:
      - "8080:8080"
    depends_on:
      - mongo
  mongo:
    image: mongo:4.2
    ports:
      - "27017:27017"